# Generated by Django 4.2.7 on 2024-04-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_room_current_position_room_is_playing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='current_position',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_playing',
        ),
        migrations.RemoveField(
            model_name='room',
            name='total_length',
        ),
        migrations.AddField(
            model_name='music',
            name='current_position',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='music',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='music',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='music',
            name='is_queued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='music',
            name='total_length',
            field=models.FloatField(default=0.0),
        ),
    ]
