# Generated by Django 4.2.7 on 2024-04-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_room_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='total_length',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
